<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Reporter.log Assert.fail occured]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="C:\Users\zilel\OneDrive\Desktop\LOK\Selenium_Project\DataDrivenFrameWork\target\surefire-reports\html\error1.jpg"> Screenshot  </a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Framework" duration-ms="2991" started-at="2021-08-04T17:56:37 AEST" finished-at="2021-08-04T17:56:40 AEST">
    <groups>
    </groups>
    <test name="LoginTest.jsp" duration-ms="2028" started-at="2021-08-04T17:56:37 AEST" finished-at="2021-08-04T17:56:39 AEST">
      <class name="testcases.LoginTest">
        <test-method status="FAIL" signature="logInAsBankManager()[pri:0, instance:testcases.LoginTest@732c2a62]" name="logInAsBankManager" duration-ms="758" started-at="2021-08-04T17:56:37 AEST" finished-at="2021-08-04T17:56:38 AEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[log in unsuccessful!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: log in unsuccessful!!!
at org.testng.Assert.fail(Assert.java:99)
at testcases.LoginTest.logInAsBankManager(LoginTest.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Reporter.log Assert.fail occured]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="C:\Users\zilel\OneDrive\Desktop\LOK\Selenium_Project\DataDrivenFrameWork\target\surefire-reports\html\error1.jpg"> Screenshot  </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- logInAsBankManager -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- LoginTest.jsp -->
    <test name="AddCustomerTest.jsp" duration-ms="910" started-at="2021-08-04T17:56:39 AEST" finished-at="2021-08-04T17:56:40 AEST">
      <class name="testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.AddCustomerTest@446293d]" name="setUp" is-config="true" duration-ms="12331" started-at="2021-08-04T17:56:25 AEST" finished-at="2021-08-04T17:56:37 AEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomerTest@446293d]" name="addCustomer" duration-ms="865" started-at="2021-08-04T17:56:39 AEST" data-provider="testData" finished-at="2021-08-04T17:56:40 AEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[John]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Depp]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SeEllox&12]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.AddCustomerTest@446293d]" name="tearDown" is-config="true" duration-ms="3806" started-at="2021-08-04T17:56:40 AEST" finished-at="2021-08-04T17:56:44 AEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.AddCustomerTest -->
    </test> <!-- AddCustomerTest.jsp -->
  </suite> <!-- Data Driven Framework -->
</testng-results>
